# Site settings
author: MOHAMED AHMED
title: 
header-img: img/home-bg.png
email: mohamed_sayed_2@hotmail.com
copyright_name: MOHAMED AHMED
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mohamedahmed620

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
